config/routes.rb
Rails.application.routes.draw do




  root to: "public/homes#top"
  get "about" =>"public/homes#about"

  # 検索機能
  get "search", to: 'searches#search'
  get "genresearch", to: 'searches#genresearch'

  get "customers/my_page" => "public/customers#show"

  scope module: :public do

    resources :items, only: [:index, :show]

    resources :cart_items, only: [:index, :update, :destroy, :create] do
    collection do
      delete :destroy_all
    end
  end

    resources :orders, only: [:new, :create, :index, :show] do
    collection do
      post :confirm
      get :complete
    end
  end

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resource :customers,only: [:edit,:update] do
      collection do
        get :unsubscribe
        patch :withdraw
      end
    end
  end

  namespace :admin do
    get "/" => "homes#top"
    resources :items,except: [:destroy]
    resources :genres,only: [:index,:create,:edit,:update,:destroy]
    resources :customers,only: [:index,:show,:edit,:update]
    resources :orders,only: [:show,:update]do
    resources :order_details,only: [:update]
  end
  end

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  devise_for :admins,skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  #belongs_toはvalidationも含む　customer_idがないと保存できない含む

  validates :postal_code,:address,:name, presence: true

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item


  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, presence: :true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :orders_details, dependent: :destroy
  belongs_to :genre

  has_one_attached :item_image
  validates :name, :introduction, :price, presence: :true

  def  add_tax_price
  (self.price * 1.10).round
  end

  def with_tax_price
    (price * 1.1).floor
  end

  def self.search_for(content)
      Item.where('name LIKE ?', '%' + content + '%')
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :customer

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum status: {
      入金待ち: 0,
      入金確認: 1,
      製作中: 2,
      発送準備中: 3,
      発送済み: 4
   }

  def subtotal
    item.with_tax_price * amount
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: {
      製作不可: 0,
      製作待ち: 1,
      製作中: 2,
      製作完了: 3,
   }

 def  add_tax_price
    (self.price * 1.10).round
 end

  def subtotal
    self.item.with_tax_price * amount
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:notice] = 'You have updated customer successfully.'
      redirect_to admin_customer_path(@customer.id)
    else
      render :edit
    end
  end

  private

  def customer_params
     params.require(:customer).permit(:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_deleted)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
    def index
        @genre = Genre.new
        @genres = Genre.all
    end

    def create
        @genre = Genre.new(genre_params)
        @genre.save
        redirect_to request.referer
    end

    def destroy
        genre = Genre.find(params[:id])
        genre.destroy
        redirect_to request.referer
    end


    def edit
        @genre = Genre.find(params[:id])
    end

    def update
        genre = Genre.find(params[:id])
        genre.update(genre_params)
        redirect_to admin_genres_path
    end

    private
     # ストロングパラメータ
    def genre_params
        params.require(:genre).permit(:name)
    end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
      @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      #リダイレクトと同時にフラッシュメッセージの実装
      flash[:notice] = 'You have created item successfully'
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = 'You have updated item successfully.'
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end

  private
  # ストロングパラメータ
  def item_params
    params.require(:item).permit(:item_image, :name, :introduction, :price, :genre_id, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
	# headerのサーチフォーム
	def search
		@content=params[:content]
		@items=Item.where(is_active:true).search_for(@content)
	end

	def genresearch
		@content=params[:content]
		@genre=Genre.find_by(name: @content)
		@items=Item.where(is_active: true, genre_id: @genre.id)
	end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <h6 style="background-color:#EEEEEE;color:dark;display:inline"><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h6>
  </div>

    <div class="row">
     <label for="id" class="col-sm-2">会員ID</label>
     <div class="col-sm-10">
      <%= @customer.id %>
     </div>
    </div>

  <%= form_with model: @customer, url: admin_customer_path, method: :patch, local:true do |f| %>
    <div class="form-group">
      <div class="row">
        <label for="name" class="col-sm-2 col-form-label">氏名</label>
        <div class="col-sm-10">
          <%= f.text_field :last_name %>
          <%= f.text_field :first_name %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
        <label for="name_kana" class="col-sm-2 col-form-label">フリガナ</label>
        <div class="col-sm-10">
          <%= f.text_field :last_name_kana %>
          <%= f.text_field :first_name_kana %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
        <label for="postal_code" class="col-sm-2 col-form-label">郵便番号</label>
        <div class="col-sm-10">
          <%= f.text_field :postal_code %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
        <label for="address" class="col-sm-2 col-form-label">住所</label>
        <div class="col-sm-10">
          <%= f.text_area :address %>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
        <label for="number" class="col-sm-2 col-form-label">電話番号</label>
        <div class="col-sm-10">
          <%= f.text_field :telephone_number %>
        </div>
       </div>
    </div>

    <div class="form-group">
      <div class="row">
        <label for="mail" class="col-sm-2 col-form-label">メールアドレス</label>
        <div class="col-sm-10">
          <%= f.text_field :email %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
        <label for="status" class="col-sm-4">会員ステータス</label>
        <div class="col-sm-8">
          <%= f.radio_button :is_deleted, false %>
          <%= f.label :is_deleted, '有効', value: false %>
          <%= f.radio_button :is_deleted, true %>
          <%= f.label :is_deleted, '退会', value: true %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.submit "変更を保存", class: "btn btn-success" %>
    </div>
  <% end %>
</div>
</form>

app/views/admin/customers/index.html.erb
<div class="container">
   <h6 style="background-color:#EEEEEE;color:dark;display:inline">会員一覧</h6>
   <table class='table'>
    <thead class="bg-light text-dark">
      <tr>
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>
          <td>
            <%= link_to admin_customer_path(customer.id) do %>
              <div><%= customer.last_name %><%= customer.first_name %></div>
            <% end %>
          </td>
          <td><%= customer.email %></td>
          <td>
            <% if customer.is_deleted == false %>
            <p class="font-weight-bold text-success">
              <%= "有効" %>
            </p>
            <% else %>
            <p class="text-secondary">
              <%= "退会" %>
            </p>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
   <h6 style="background-color:#EEEEEE;color:dark;display:inline"><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h6>
   <div class='row'>
     <div class="col-12 px-5 px-sm-0 mx-auto">
        <table class="table table-borderless">
          <tr>
            <td>会員ID</td>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <td>氏名</td>
            <td><%= @customer.last_name %> <%= @customer.first_name %></td>
          </tr>
          <tr>
            <td>フリガナ</td>
            <td><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></td>
          </tr>
          <tr>
            <td>郵便番号</td>
            <td><%= @customer.postal_code %></td>
          </tr>
          <tr>
            <td>住所</td>
            <td><%= @customer.address %></td>
          </tr>
          <tr>
            <td>電話番号</td>
            <td><%= @customer.telephone_number %></td>
          <tr>
            <td>メールアドレス</td>
            <td><%= @customer.email %></td>
          </tr>
          <tr>
            <td>会員ステータス</td>
            <td><% if @customer.is_deleted == false %>
            <p class="font-weight-bold text-success">
              <%= "有効" %>
            </p>
            <% else %>
            <p class="text-secondary">
              <%= "退会" %>
            </p>
            <% end %>
            </td>
          </tr>
          <tr>
            <td><%= link_to '編集する', edit_admin_customer_path(@customer), class: "btn btn-success edit_admin_customer_#{@customer.id}" %></td>
            <td><%= link_to '注文履歴一覧を見る', admin_path , class: "btn btn-primary" %></td>
          </tr>
        </table>
      </div>
   </div>
</div>