config/routes.rb
Rails.application.routes.draw do




  root to: "public/homes#top"
  get "about" =>"public/homes#about"

  # 検索機能
  get "search", to: 'searches#search'
  get "genresearch", to: 'searches#genresearch'

  get "customers/my_page" => "public/customers#show"

  scope module: :public do

    resources :items, only: [:index, :show]

    resources :cart_items, only: [:index, :update, :destroy, :create] do
    collection do
      delete :destroy_all
    end
  end

    resources :orders, only: [:new, :create, :index, :show] do
    collection do
      post :confirm
      get :complete
    end
  end

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resource :customers,only: [:edit,:update] do
      collection do
        get :unsubscribe
        patch :withdraw
      end
    end
  end

  namespace :admin do
    get "/" => "homes#top"
    resources :items,except: [:destroy]
    resources :genres,only: [:index,:create,:edit,:update,:destroy]
    resources :customers,only: [:index,:show,:edit,:update]
    resources :orders,only: [:show,:update]do
    resources :order_details,only: [:update]
  end
  end

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  devise_for :admins,skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  #belongs_toはvalidationも含む　customer_idがないと保存できない含む

  validates :postal_code,:address,:name, presence: true

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item


  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, presence: :true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :orders_details, dependent: :destroy
  belongs_to :genre

  has_one_attached :item_image
  validates :name, :introduction, :price, presence: :true

  def  add_tax_price
  (self.price * 1.10).round
  end

  def with_tax_price
    (price * 1.1).floor
  end

  def self.search_for(content)
      Item.where('name LIKE ?', '%' + content + '%')
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :customer

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum status: {
      入金待ち: 0,
      入金確認: 1,
      製作中: 2,
      発送準備中: 3,
      発送済み: 4
   }

  def subtotal
    item.with_tax_price * amount
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: {
      製作不可: 0,
      製作待ち: 1,
      製作中: 2,
      製作完了: 3,
   }

 def  add_tax_price
    (self.price * 1.10).round
 end

  def subtotal
    self.item.with_tax_price * amount
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
    def index
        @genre = Genre.new
        @genres = Genre.all
    end

    def create
        @genre = Genre.new(genre_params)
        @genre.save
        redirect_to request.referer
    end

    def destroy
        genre = Genre.find(params[:id])
        genre.destroy
        redirect_to request.referer
    end


    def edit
        @genre = Genre.find(params[:id])
    end

    def update
        genre = Genre.find(params[:id])
        genre.update(genre_params)
        redirect_to admin_genres_path
    end

    private
     # ストロングパラメータ
    def genre_params
        params.require(:genre).permit(:name)
    end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
      @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      #リダイレクトと同時にフラッシュメッセージの実装
      flash[:notice] = 'You have created item successfully'
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = 'You have updated item successfully.'
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end

  private
  # ストロングパラメータ
  def item_params
    params.require(:item).permit(:item_image, :name, :introduction, :price, :genre_id, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

 def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
 end

 def update
    @order = Order.find(params[:id])
      @order.update(order_params)
      if params[:order][:status] == "入金確認"
        @order.order_details.update(making_status:1)
      end
    redirect_to request.referer
 end


 private
  # ストロングパラメータ
  def order_params
    params.require(:order).permit(:name, :postal_code, :address, :payment_method, :status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
	# headerのサーチフォーム
	def search
		@content=params[:content]
		@items=Item.where(is_active:true).search_for(@content)
	end

	def genresearch
		@content=params[:content]
		@genre=Genre.find_by(name: @content)
		@items=Item.where(is_active: true, genre_id: @genre.id)
	end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <h6 style="background-color:#EEEEEE;color:dark;display:inline">ジャンル編集</h6>
  <div class="row">
    <%= form_with model: @genre, url: admin_genre_path(@genre.id), method: :patch do |f| %>
    <table class='table table-borderless'>
        <thead>
          <tr>
            <th><%= f.label :name,"ジャンル名" %></th>
            <th><%= f.text_field :name, class: 'form-control book_title' %></th>
            <th><%= f.submit "変更を保存",class: 'btn btn-success' %></th>
          </tr>
        </thead>
        <% end %>
    </table>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container pl-4">
  <h6 style="background-color:#EEEEEE;color:dark;display:inline" class="offset-1">ジャンル一覧・追加</h6>

  <%= form_with model: @genre,url: admin_genres_path,local:true do |f| %>
    <table class='table table-borderless'>
      <thead>
          <tr>
            <th><%= f.label :ジャンル名 %></th>
            <th><%= f.text_field :name, :value => "ケーキ", class: 'form-control genre_name',placeholder:"ジャンル名" %></th>
            <th><%= f.submit "新規登録" ,class: 'btn btn-success' %></th>
          </tr>
      </thead>
    </table>
  <% end %>

    <table class='table'>
      <thead class="bg-light text-dark">
        <tr>
          <th>ジャンル</th>
        </tr>
      </thead>
      <tbody>
          <% @genres.each do |genre| %>
        <tr>
          <td><%=  genre.name %></td>
          <td>
            <%= link_to "編集する", edit_admin_genre_path(genre),class: 'btn btn-sm btn-success' %>
            <%= link_to "消去する", admin_genre_path(genre), method: :delete,class: "btn btn-sm btn-danger" %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
</div>

app/views/admin/items/edit.html.erb
<div class="container">
   <h6 style="background-color:#EEEEEE;color:dark;display:inline">商品編集</h6>

   <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
     <%= form_with model: @item, url: admin_item_path(@item.id), method: :patch, local:true do |f| %>
      <div class="form-group">
        <div class="row">
          <label for="item_image" class="col-sm-3 col-form-label">商品画像</label>
          <div class="col-sm-9">
          <%= f.file_field :item_image, accept: "item_image/*" %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="row">
          <label for="item_name" class="col-sm-3 col-form-label">商品名</label>
          <div class="col-sm-9">
           <%= f.text_field :name, placeholder:"商品名" %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="row">
          <label for="item_introduction" class="col-sm-3 col-form-label">商品説明</label>
          <div class="col-sm-9">
            <%= f.text_area :introduction, size: "40x5",placeholder:"ここに説明文を記述します" %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="row">
          <label for="item_genre" class="col-sm-3 col-form-label">ジャンル</label>
          <div class="col-sm-9">
            <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "選択してください" %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="row">
          <label for="item_price" class="col-sm-3 col-form-label">税抜価格</label>
          <div class="col-sm-9">
           <%= f.text_field :price, placeholder:"1000" %><span>円</span>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="row">
          <label for="item_introduction" class="col-sm-4">販売ステータス</label>
          <div class="col-sm-8">
           <%= f.radio_button :is_active, true %>
           <%= f.label :is_active, '販売中', value: true %>
           <%= f.radio_button :is_active, false %>
           <%= f.label :is_active, '販売停止中', value: false %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <%= f.submit "変更を保存", class: "btn btn-success" %>
      </div>
     <% end %>
   </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <h6 style="background-color:#EEEEEE;color:dark;display:inline">商品一覧</h6>

  <%= link_to new_admin_item_path, class: 'nav-link' do %>
    <i class='fa-solid fa-circle-plus'></i>
  <% end %>

  <table class='table'>
      <thead class="bg-light text-dark">
        <tr>
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
          <th>ステータス</th>
        </tr>
      </thead>
    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td>
            <p class="text-primary">
              <%= link_to item.name ,admin_item_path(item.id) %>
            </p>
          </td>
          <td><%= item.price.to_s(:delimited) %></td>
          <td><%= item.genre.name %></td>
          <td>
            <% if item.is_active == true %>
            <p class="font-weight-bold text-success">
              <%= "販売中" %>
            </p>
            <% else %>
            <p class="text-secondary">
              <%= "販売停止中" %>
            </p>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/items/new.html.erb
<div class="container">
   <h6 style="background-color:#EEEEEE;color:dark;display:inline">商品新規登録</h5>

  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
     <%= form_with model: @item, url: admin_items_path, method: :post, local:true do |f| %>
      <div class="form-group">
        <div class="row">
          <label for="item_image" class="col-sm-3 col-form-label">商品画像</label>
          <div class="col-sm-9">
          <%= f.file_field :item_image, accept: "item_image/*" %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="row">
          <label for="item_name" class="col-sm-3 col-form-label">商品名</label>
          <div class="col-sm-9">
           <%= f.text_field :name, :value => "ケーキ" %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="row">
          <label for="item_introduction" class="col-sm-3 col-form-label">商品説明</label>
          <div class="col-sm-9">
            <%= f.text_area :introduction, size: "40x5", :value => "ケーキの説明文"  %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="row">
          <label for="item_genre" class="col-sm-3 col-form-label">ジャンル</label>
          <div class="col-sm-9">
            <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "選択してください" %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="row">
          <label for="item_price" class="col-sm-3 col-form-label">税抜価格</label>
          <div class="col-sm-9">
           <%= f.text_field :price, :value => "1000"  %><span>円</span>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="row">
          <label for="item_status" class="col-sm-4">販売ステータス</label>
          <div class="col-sm-8">
             <%= f.radio_button :is_active, true %>
             <%= f.label :is_active, '販売中', value: true %>
             <%= f.radio_button :is_active, false %>
             <%= f.label :is_active, '販売停止中', value: false %>
          </div>
        </div>
      </div>
      <div class="form-group mx-auto" style="width: 100px;">
        <%= f.submit "新規登録", class: "btn btn-success" %>
      </div>
     <% end %>
   </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
   <h6 style="background-color:#EEEEEE;color:dark;display:inline">商品詳細</h6>
   <div class="row">
    <div class="col-3 px-sm-0 mx-auto">
      <% if @item.item_image.attached? %>
        <%= image_tag @item.item_image, size: "200x150" %>
      <% else %>
        <%= image_tag 'no_image.jpg', size: "200x200" %>
      <% end %>
    </div>
    <div class="col-9 px-5 px-sm-0 mx-auto">
      <table class="table table-borderless">
        <tr>
          <td>商品名</td>
          <td><%= @item.name %></td>
        </tr>
        <tr>
          <td>商品説明</td>
          <td><%= @item.introduction %></td>
        </tr>
        <tr>
          <td>ジャンル</td>
          <td><%= @item.genre.name %></td>
        </tr>
        <tr>
          <td>税込価格（税抜価格）</td>
          <td><%= @item.add_tax_price.to_s(:delimited) %><span>（<%= @item.price.to_s(:delimited) %>）</span>円</td>
        </tr>
        <tr>
          <td>販売ステータス</td>
          <td><% if @item.is_active == true %>
          <p class="font-weight-bold text-success">
            <%= "販売中" %>
          </p>
          <% else %>
          <p class="text-secondary">
            <%= "販売停止中" %>
            </p>
          <% end %>
          </td>
        </tr>
        <tr>
          <td><%= link_to '編集する', edit_admin_item_path(@item), class: "btn btn-sm btn-success edit_admin_item_#{@item.id}" %></td>
        </tr>
       </table>
      </div>
   </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <h6 style="background-color:#EEEEEE;color:dark;display:inline">注文履歴詳細</h6>
  <div ="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <table class="table table-borderless">
          <tr>
            <td>購入者</td>
            <td><%= @order.name %></td>
          </tr>
          <tr>
            <td>注文日</td>
            <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
          </tr>
          <tr>
            <td>配送先</td>
            <td>
              <%= @order.postal_code %> <%= @order.address %></br>
              <%= @order.name %>
            </td>
          </tr>
          <tr>
            <td>支払方法</td>
            <td><%= @order.payment_method_i18n %></td>
          </tr>
          <tr>
            <td>注文ステータス</td>
            <td>
              <%= form_with model: @order, url: admin_order_path(@order.id),method: :patch, local:true do |f| %>
                <%= f.select :status, Order.statuses.keys.to_a %>
                <%= f.submit "更新", class: "btn btn-sm btn-success" %>
              <% end %>
            </td>
          </tr>
        </table>
      </div>
  </div>

  <div class="row">
    <div class="col-md-8">
      <table class='table'>
        <thead class="bg-light text-dark">
          <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
          </tr>
        </thead>
        <% @sum = 0 %>
        <tbody>
          <% @order_details.each do |order_detail| %>
            <tr>
              <td><%= order_detail.item.name %></td>
              <td><%= order_detail.add_tax_price.to_s(:delimited) %></td>
              <td><%= order_detail.amount %></td>
              <td><%= order_detail.subtotal.to_s(:delimited) %>
                 <% @sum += order_detail.subtotal %>
              </td>
              <td>
                <%= form_with model: order_detail, url: admin_order_order_detail_path(order_id: @order.id, id: order_detail.id),method: :patch, local:true do |f| %>
                  <%= f.select :making_status, OrderDetail.making_statuses.keys.to_a %>
                  <%= f.submit "更新", class: "btn btn-sm btn-success" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="col-md-4">
　　　<table class="table table-borderless">
        <tr>
          <th>商品合計</th>
          <td><%= @sum.to_s(:delimited) %>円</td>
        </tr>
        <tr>
          <th>送料</th>
          <td>800円</td>
        </tr>
        <tr>
        　<th>請求金額合計</th>
          <td><%= (@sum + 800).to_s(:delimited) %>円</td>
        </tr>
      </table>
    </div>
  </div>
</div>