config/routes.rb
Rails.application.routes.draw do




  root to: "public/homes#top"
  get "about" =>"public/homes#about"

  # 検索機能
  get "search", to: 'searches#search'
  get "genresearch", to: 'searches#genresearch'

  get "customers/my_page" => "public/customers#show"

  scope module: :public do

    resources :items, only: [:index, :show]

    resources :cart_items, only: [:index, :update, :destroy, :create] do
    collection do
      delete :destroy_all
    end
  end

    resources :orders, only: [:new, :create, :index, :show] do
    collection do
      post :confirm
      get :complete
    end
  end

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resource :customers,only: [:edit,:update] do
      collection do
        get :unsubscribe
        patch :withdraw
      end
    end
  end

  namespace :admin do
    get "/" => "homes#top"
    resources :items,except: [:destroy]
    resources :genres,only: [:index,:create,:edit,:update,:destroy]
    resources :customers,only: [:index,:show,:edit,:update]
    resources :orders,only: [:show,:update]do
    resources :order_details,only: [:update]
  end
  end

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  devise_for :admins,skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  #belongs_toはvalidationも含む　customer_idがないと保存できない含む

  validates :postal_code,:address,:name, presence: true

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item


  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, presence: :true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :orders_details, dependent: :destroy
  belongs_to :genre

  has_one_attached :item_image
  validates :name, :introduction, :price, presence: :true

  def  add_tax_price
  (self.price * 1.10).round
  end

  def with_tax_price
    (price * 1.1).floor
  end

  def self.search_for(content)
      Item.where('name LIKE ?', '%' + content + '%')
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :customer

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum status: {
      入金待ち: 0,
      入金確認: 1,
      製作中: 2,
      発送準備中: 3,
      発送済み: 4
   }

  def subtotal
    item.with_tax_price * amount
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: {
      製作不可: 0,
      製作待ち: 1,
      製作中: 2,
      製作完了: 3,
   }

 def  add_tax_price
    (self.price * 1.10).round
 end

  def subtotal
    self.item.with_tax_price * amount
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
    def index
        @genre = Genre.new
        @genres = Genre.all
    end

    def create
        @genre = Genre.new(genre_params)
        @genre.save
        redirect_to request.referer
    end

    def destroy
        genre = Genre.find(params[:id])
        genre.destroy
        redirect_to request.referer
    end


    def edit
        @genre = Genre.find(params[:id])
    end

    def update
        genre = Genre.find(params[:id])
        genre.update(genre_params)
        redirect_to admin_genres_path
    end

    private
     # ストロングパラメータ
    def genre_params
        params.require(:genre).permit(:name)
    end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
      @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      #リダイレクトと同時にフラッシュメッセージの実装
      flash[:notice] = 'You have created item successfully'
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = 'You have updated item successfully.'
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end

  private
  # ストロングパラメータ
  def item_params
    params.require(:item).permit(:item_image, :name, :introduction, :price, :genre_id, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
	# headerのサーチフォーム
	def search
		@content=params[:content]
		@items=Item.where(is_active:true).search_for(@content)
	end

	def genresearch
		@content=params[:content]
		@genre=Genre.find_by(name: @content)
		@items=Item.where(is_active: true, genre_id: @genre.id)
	end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/homes/top.html.erb
<div class="container">
  <h6 style="background-color:#EEEEEE;color:dark;display:inline">注文履歴一覧</h6>
  <table class='table'>
    <thead class="bg-light text-dark">
      <tr>
        <th>購入日時</th>
        <th>購入者</th>
        <th>注文個数</th>
        <th>注文ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td>
            <%= link_to order.updated_at.strftime('%Y/%m/%d %H:%M:%S') ,admin_order_path(order.id) %>
          </td>
          <td><%= order.name %></td>
          <td><%= order.order_details.sum(:amount) %></td>
          <td><%= order.status %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/searches/_form.html.erb
<!--headerのサーチフォーム-->
<%= form_with url: search_path, method: :get, local: true do |f| %>
  <%= f.text_field :content %>
  <%= f.submit '🔍' %>
<% end %>

app/views/searches/genresearch.html.erb
<div class="container mt-3 mx-auto">
  <div class="row">
    <h1>商品一覧</h1>
  </div>
  <div class="row justify-content-center">

  </div>

<div class="row justify-content-center">
    <div class="col-xl-3 col-md-3">
      <% @items.each do |item| %>
        <% if item.item_image.attached? %>
          <%= image_tag item.item_image, size: "200x200" %>
        <% else %>
          <%= image_tag 'no_image', size: "200x200" %>
        <% end %>
        <p><%= link_to item.name, item_path(item.id) %></p>
        <p>¥<%= item.price.to_s(:delimited) %></p>
      <% end %>
    </div>
</div>

app/views/searches/search.html.erb
<%if customer_signed_in? %>
  <div class="container mt-3 mx-auto">
    <div class="row">
      <h3>Items search for "<%= @content %>"</h3>
    </div>
    <div class="row justify-content-center">
      <% count = 0 %>
      <% @items.each do |item| %>
      <div class="col-xl-3 col-md-3">
        <% if item.item_image.attached? %>
          <%= image_tag item.item_image, size: "150x100" %>
        <% else %>
          <%= image_tag 'no_image', size: "150x100" %>
        <% end %>
        <p><%= link_to item.name, item_path(item.id) %></p>
        <p>¥<%= item.price.to_s(:delimited) %></p>
      </div>
      　<% count += 1 %>
      <% end %>
    </div>
    <h2>検索結果<%= count%>件</h2>
  </div>
  <% elsif admin_signed_in? %>
  <div class="container mt-3 mx-auto">
    <div class="row">
      <h3>Items search for "<%= @content %>"</h3>
    </div>
    <div class="row justify-content-center">
      <% count = 0 %>
      <% @items.each do |item| %>
      <div class="col-xl-3 col-md-3">
        <% if item.image_id.attached? %>
          <%= image_tag item.image_id, size: "150x100" %>
        <% else %>
          <%= image_tag 'no_image', size: "150x100" %>
        <% end %>
        <p><%= link_to item.name, admin_item_path(item.id) %></p>
        <p>¥<%= item.price.to_s(:delimited) %></p>
      </div>
      　<% count += 1 %>
      <% end %>
    </div>
    <p>検索結果<%= count%>件</p>
　</div>
  <%end%>