config/routes.rb
Rails.application.routes.draw do




  root to: "public/homes#top"
  get "about" =>"public/homes#about"

  # 検索機能
  get "search", to: 'searches#search'
  get "genresearch", to: 'searches#genresearch'

  get "customers/my_page" => "public/customers#show"

  scope module: :public do

    resources :items, only: [:index, :show]

    resources :cart_items, only: [:index, :update, :destroy, :create] do
    collection do
      delete :destroy_all
    end
  end

    resources :orders, only: [:new, :create, :index, :show] do
    collection do
      post :confirm
      get :complete
    end
  end

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resource :customers,only: [:edit,:update] do
      collection do
        get :unsubscribe
        patch :withdraw
      end
    end
  end

  namespace :admin do
    get "/" => "homes#top"
    resources :items,except: [:destroy]
    resources :genres,only: [:index,:create,:edit,:update,:destroy]
    resources :customers,only: [:index,:show,:edit,:update]
    resources :orders,only: [:show,:update]do
    resources :order_details,only: [:update]
  end
  end

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  devise_for :admins,skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  #belongs_toはvalidationも含む　customer_idがないと保存できない含む

  validates :postal_code,:address,:name, presence: true

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item


  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, presence: :true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :orders_details, dependent: :destroy
  belongs_to :genre

  has_one_attached :item_image
  validates :name, :introduction, :price, presence: :true

  def  add_tax_price
  (self.price * 1.10).round
  end

  def with_tax_price
    (price * 1.1).floor
  end

  def self.search_for(content)
      Item.where('name LIKE ?', '%' + content + '%')
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :customer

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum status: {
      入金待ち: 0,
      入金確認: 1,
      製作中: 2,
      発送準備中: 3,
      発送済み: 4
   }

  def subtotal
    item.with_tax_price * amount
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: {
      製作不可: 0,
      製作待ち: 1,
      製作中: 2,
      製作完了: 3,
   }

 def  add_tax_price
    (self.price * 1.10).round
 end

  def subtotal
    self.item.with_tax_price * amount
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
      @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      #リダイレクトと同時にフラッシュメッセージの実装
      flash[:notice] = 'You have created item successfully'
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = 'You have updated item successfully.'
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end

  private
  # ストロングパラメータ
  def item_params
    params.require(:item).permit(:item_image, :name, :introduction, :price, :genre_id, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
	# headerのサーチフォーム
	def search
		@content=params[:content]
		@items=Item.where(is_active:true).search_for(@content)
	end

	def genresearch
		@content=params[:content]
		@genre=Genre.find_by(name: @content)
		@items=Item.where(is_active: true, genre_id: @genre.id)
	end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container-fluid" style="background-color: #550000">
    <div class="row">
      <div class="col border-top">
        <div class= "d-flex justify-content-center mt-2 mb-2">
          <a href="#" class="text-light"><i class="fab fa-twitter-square fa-2x"></i></a>
          <a href="#" class="mx-4 text-light"><i class="fab fa-instagram fa-2x"></i></a>
          <a href="#" class="text-light"><i class="far fa-envelope fa-2x"></i></a>
        </div>
        <div class="text-center text-light">© Nagano Cake.inc</div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg" style="background-color: #550000">
    <div class="container">
      <a class="navbar-brand" href="/"><%= image_tag 'naganocake.png', size: '120x120' %></a>
        <ul class="navbar-nav ml-auto">
        <!--会員-->
      <% if customer_signed_in? %>
        <li class="mx-5 text-light">ようこそ、<%= current_customer.last_name %>さん！</li>
        <li>
          <%= link_to "マイページ",customers_my_page_path,class: 'btn btn-sm btn-outline-light mr-2' %>
        </li>
        <li>
          <%= link_to "商品一覧",items_path,class: 'btn btn-sm btn-outline-light mr-2' %>
        </li>
        <li>
          <%= link_to "カート",cart_items_path,class: 'btn btn-sm btn-outline-light mr-2' %>
        </li>
        <li>
          <%= link_to "ログアウト",destroy_customer_session_path,method: :delete,class: 'btn btn-sm btn-outline-light mr-2' %>
        </li>
      <!--管理者-->
      <% elsif admin_signed_in? %>
        <li>
          <%= link_to "商品一覧",admin_items_path,class: 'btn btn-sm btn-outline-light mr-2' %>
        </li>
        <li>
          <%= link_to "会員一覧",admin_customers_path,class: 'btn btn-sm btn-outline-light mr-2' %>
        </li>
        <li>
          <%= link_to "注文履歴一覧",admin_path,class: 'btn btn-sm btn-outline-light mr-2' %>
        </li>
        <li>
          <%= link_to "ジャンル一覧",admin_genres_path,class: 'btn btn-sm btn-outline-light mr-2' %>
        </li>
        <li>
          <%= link_to "ログアウト",destroy_admin_session_path,method: :delete,class: 'btn btn-sm btn-outline-light mr-2' %>
        </li>
      <% else %>
        <li>
          <%= link_to "About",about_path,class: 'btn btn-sm btn-outline-light mr-2' %>
        </li>
        <li>
          <%= link_to "商品一覧",items_path,class: 'btn btn-sm btn-outline-light mr-2' %>
        </li>
        <li>
          <%= link_to "新規登録",new_customer_registration_path,class: 'btn btn-sm btn-outline-light mr-2' %>
        </li>
        <li>
          <%= link_to "ログイン",new_customer_session_path,class: 'btn btn-sm btn-outline-light mr-2' %>
        </li>
        <li>
          <%= link_to "管理者ログイン",new_admin_session_path,class: 'btn btn-sm btn-outline-light mr-2' %>
        </li>
      <% end %>
      </ul>
      <%= render 'searches/form', items: @item %>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!--googleform使うため下記2つ追加し,application.scssに記載-->
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Shizuru&display=swap" rel="stylesheet">
  </head>

  <body style="background-color: #f3ecef">
    <%= render 'layouts/header' %>
      <main>
        <p id="notice"><%= notice %></p>
        <%= yield %>
      </main>
    <%= render 'layouts/footer' %>
  </body>
</html>